#ifndef _1K161_H
#define _1K161_H
enum {
	GNSS_STATE_QUIET = 0,
	GNSS_STATE_RESET,
	GNSS_STATE_WAIT_FOR_RESET,
	GNSS_STATE_SET_BINARY,
	GNSS_STATE_WAIT_FOR_BINARY,
	GNSS_STATE_INC_USART_CFG,
	GNSS_STATE_USART_RECONFIG,
	GNSS_STATE_FOUND,
	GNSS_STATE_CHANNEL_CFG_RESULT,
	GNSS_STATE_SELFTEST_RESULT,
};

#endif
